services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_PORT: 7003
    ports:
      - 127.0.0.1:7003:7003
