# fly.toml app configuration file generated for schachmatt-ulm-ergebnisse on 2025-02-10T11:50:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'schachmatt-ulm-ergebnisse'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
